# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando a Inteligência Artificial no Google Colab
"""

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

from google import genai

client = genai.Client()

resposta = client.models.generate_content(model="gemini-2.5-flash", contents="Minha página no Instagram está crescendo, e estou tendo dificuldades em responder aos comentários e mensagens como antes. Como posso fazer para me manter próximo ao meu público dentro deste cenário?")

print(resposta.text)

"""## Estruturas de Repetição"""

import time

n = 1

while n <= 5:
  print("*")
  n = n + 1
  time.sleep(1)