# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando a Inteligência Artificial no Google Colab
"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')
client = genai.Client()
chat = client.chats.create(model="gemini-2.5-flash")

"""## Criando um Chatbot"""

prompt = input("Digite a sua pergunta: ")
print()

while "tchau" not in prompt.lower():
  resposta = chat.send_message(prompt)

  print(f"Chat IA: {resposta.text}")
  print()

  prompt = input("Pergunta: ")
  print()

