# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando a Inteligência Artificial no Google Colab
"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')
client = genai.Client()
chat = client.chats.create(model="gemini-2.5-flash")

prompt = input("Luis: ")
print()

while "tchau" not in prompt.lower():
  resposta = chat.send_message(prompt)

  print(f"InAr: {resposta.text}")
  print()

  prompt = input("Luis: ")
  print()

"""## Estruturas de Dados

### Listas
"""

nomes = ["Maria Silva", "João Santos", "Ana Oliveira", "Pedro Costa", "Juliana Pereira"]
medias = [8.9, 7.5, 4.2, 1.4, 9.5]

n = 0

while n < len(nomes):
  medias[n] = medias[n] + 1

  if medias[n] > 10:
    medias[n] = 10

  print(f"Nome: {nomes[n]} \t Média: {medias[n]}")
  n = n + 1

"""### Obtendo elementos de trás para frente"""

n = len(nomes) * -1
i = -1

while n <= i:
  print(f"Nome: {nomes[i]} \t Média: {medias[i]}")
  i = i - 1

"""### Particionando Lista"""

nomes[1:3]

nomes[1:]

nomes[:4]

"""### Adicionando novo Elemento"""

nomes.append("Fabio Carrara")
nomes

nomes.extend(["Luis Paulo", "Fonseca Araujo"])

nomes

"""### Acessando uma Lista dentro de outra Lista"""

nomes[7][1]

nomes.remove("Luis Paulo")
nomes

nomes.pop()
nomes

