# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando a Inteligência Artificial no Google Colab
"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')
client = genai.Client()
chat = client.chats.create(model="gemini-2.5-flash")

prompt = input("Luis: ")
print()

while "tchau" not in prompt.lower():
  resposta = chat.send_message(prompt)

  print(f"InAr: {resposta.text}")
  print()

  prompt = input("Luis: ")
  print()

"""## Estruturas de Dados

### Dicionários
"""

nomes_medias = {
    "Maria Silva": 8.9,
    "João Santos": 7.5,
    "Ana Oliveira": 4.2,
    "Pedro Costa": 1.4,
    "Juliana Pereira": 9.5
}

nomes_medias["Maria Silva"]

nomes_medias.get("Maria Silva")

nomes_medias.pop("Maria Silva")

nomes_medias

nomes_medias.items()

nomes_medias.keys()

nomes_medias.values()

