# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando a Inteligência Artificial no Google Colab
"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')
client = genai.Client()
chat = client.chats.create(model="gemini-2.5-flash")

prompt = input("Luis: ")
print()

while "tchau" not in prompt.lower():
  resposta = chat.send_message(prompt)

  print(f"InAr: {resposta.text}")
  print()

  prompt = input("Luis: ")
  print()

"""# Estrutura de Repetição - Loop For"""

dicionario = [
    {"nome": "Maria Silva", "media": 8.9},
    {"nome": "João Santos", "media": 7.5},
    {"nome": "Ana Oliveira", "media": 4.2},
    {"nome": "Pedro Costa", "media": 1.4}
]

n = 0

while n < len(dicionario):
  print(dicionario[n])
  n += 1

for elemento in dicionario:
  print(elemento)

for numero in range(5):
  print(numero)

for numero in range(2, 7):
  print(numero)

for numero in range(2, 20, 3):
  print(numero)

pessoa = {
    "nome": "Luis Paulo",
    "idade": 19,
    "altura": 1.75
}

print(pessoa)

for dado in pessoa:
  print(dado)

for chave, valor in pessoa.items():
  print(f"Chave: {chave} \t| Valor: {valor}")

for numero in range(11):
  if numero % 2 == 0:
    print(f"O número {numero} é par")
  else:
    print(f"O número {numero} é ímpar")

for numero in range(11):
  if numero % 3 == 0:
    print(numero)

