# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando a Inteligência Artificial no Google Colab
"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')
client = genai.Client()
chat = client.chats.create(model="gemini-2.5-flash")

prompt = input("Luis: ")
print()

while "tchau" not in prompt.lower():
  resposta = chat.send_message(prompt)

  print(f"InAr: {resposta.text}")
  print()

  prompt = input("Luis: ")
  print()

"""# Funções"""

texto1 = "  LUis PAULO torres  de  OlIveirA   "
texto2 = "   lUiS   pAuLo   OlIvEiRa   ";
texto3 = "mArIa    aPaReCiDa   dOs sAnToS  ";
texto4 = "    cArLoS   eDuArDo    dE  sOuZa   ";
texto5 = "   aNa   bEaTrIz    rIbEiRo mArTiNs ";
texto6 = "  pEdRo   hEnRiQuE   gOmEs    ";

def corrigir_texto(texto):
  texto = texto.upper()
  palavras = texto.split()
  texto = " ".join(palavras)
  print(texto)

corrigir_texto(texto1)
corrigir_texto(texto2)
corrigir_texto(texto3)
corrigir_texto(texto4)
corrigir_texto(texto5)
corrigir_texto(texto6)
#

