# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando a Inteligência Artificial no Google Colab
"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')
client = genai.Client()
chat = client.chats.create(model="gemini-2.5-flash")

prompt = input("Luis: ")
print()

while "tchau" not in prompt.lower():
  resposta = chat.send_message(prompt)

  print(f"InAr: {resposta.text}")
  print()

  prompt = input("Luis: ")
  print()

"""# Funções"""

import random

texto1 = "  LUis PAULO torres  de  OlIveirA   "
texto2 = "   lUiS   pAuLo   OlIvEiRa   ";
texto3 = "mArIa    aPaReCiDa   dOs sAnToS  ";
texto4 = "    cArLoS   eDuArDo    dE  sOuZa   ";
texto5 = "   aNa   bEaTrIz    rIbEiRo mArTiNs ";
texto6 = "  pEdRo   hEnRiQuE   gOmEs    ";

salas = ["Sala 1", "Sala 2", "Sala 3"]

def texto_corrigido(texto):
  return " ".join(texto.upper().split())

def alocar_aluno(nome, salas):
  aluno = {
      "nome": texto_corrigido(nome),
      "sala": random.choice(salas)
  }

  print(aluno)

alocar_aluno(texto1, salas)
alocar_aluno(texto2, salas)
alocar_aluno(texto3, salas)
alocar_aluno(texto4, salas)
alocar_aluno(texto5, salas)
alocar_aluno(texto6, salas)



"""# Desafio dos E-mails"""

conteudos = [
    "Prezados, Seguem em anexo as notas e os principais pontos decididos na reunião de hoje de manhã sobre o Projeto Fênix. Por favor, revisem as tarefas atribuídas a cada um e atualizem o status no Jira até sexta-feira. Atenciosamente, Carlos Silva Gerente de Projetos",
    "Olá, Luis! Sua inscrição no 'Workshop Avançado de Python: Do Dev ao DevOps' foi confirmada com sucesso! O evento acontecerá de forma online no dia 15 de Junho, às 19h. O link de acesso à transmissão será enviado 1 hora antes do início. Até lá! Equipe TechLearn",
    "Olá, Boas notícias! Seu pedido já foi processado pela nossa logística e está a caminho. Você pode rastrear a entrega utilizando o código de rastreamento: BR837462910X. Obrigado por comprar conosco! Suporte E-Commerce Modas",
    "Prezada equipe, Informamos que no próximo domingo, entre 02:00 e 06:00 (horário de Brasília), nossa infraestrutura passará por uma manutenção preventiva na nuvem. Durante esse período, o banco de dados e as APIs do portal de cobrança estarão temporariamente indisponíveis. Contamos com a compreensão de todos. Time de DevOps e Infraestrutura",
    "Oi, família! Passando para lembrar que este domingo vamos comemorar o aniversário da vó na churrascaria do costume. Por favor, me confirmem quem vai até quinta para eu poder fechar o número exato de lugares na reserva. Beijos, Mariana",
    "Prezado usuário, Identificamos uma tentativa de login incomum na sua conta vinda de um dispositivo desconhecido e de uma localização fora do seu padrão. Por segurança, bloqueamos temporariamente a sessão. Se não foi você, recomendamos alterar sua senha imediatamente. Equipe de Segurança da Informação",
    "Prezado Dr. Roberto, Conforme conversamos por telefone, segue em anexo a nossa proposta comercial detalhada para a automação do fluxo de remessas e conciliação bancária da sua empresa. Ficamos à disposição para agendar uma reunião de alinhamento técnico. Cordialmente, Lucas Mendes Diretor de Negócios",
    "Falta pouco para o seu acesso expirar! Notamos que sua assinatura Premium anual termina em 5 dias. Para não perder o acesso aos relatórios automatizados e dashboards exclusivos, renove agora com 15% de desconto utilizando o cupom RENOVA15. Não perca essa chance! Time Spotify & Conteúdo",
    "Olá, Paulo, Gostaríamos de agradecer o seu tempo e dedicação durante todo o nosso processo seletivo. Ficamos muito impressionados com sua sólida experiência em arquitetura .NET e bancos de dados SQL Server. É com grande prazer que gostaríamos de avançar para a fase de proposta oficial. Qual o seu melhor horário para uma call amanhã? Abraços, Alana Ramos Talent Acquisition",
    "Olá, suporte. Estou tentando gerar a guia de pagamento para o serviço de marcas (código 373), mas o sistema está retornando um erro de timeout ao tentar comunicar com a API de cobrança central. Poderiam verificar se há alguma instabilidade nelas? Usuário: Luis Paulo ID da Guia: 5542",
    "Atenção, passageiro! O check-in para o seu voo LA3492 com destino a São Paulo (CGH) já está disponível no nosso aplicativo. Economize tempo no aeroporto realizando o procedimento digital e emitindo seu cartão de embarque agora mesmo. Boa viagem! Linhas Aéreas Latam",
    "Parabéns pelo seu dia! Para celebrar mais um ano da sua vida, preparamos um presente: você ganhou um voucher de R$ 50,00 para usar em qualquer categoria do nosso site durante todo o mês do seu aniversário. Use o código: NIVER50 no carrinho. Aproveite! Equipe de Marketing ClubeVantagens",
    "Fala, time! Chegou a hora de celebrar todas as nossas metas batidas e entregas de software deste ano! Nosso tradicional Happy Hour será na próxima sexta-feira, a partir das 18h, no pub do centro. O open bar e o buffet são por conta da empresa. Contamos com a presença de todos! Recursos Humanos",
    "Olá, Estamos atualizando nossos Termos de Serviço para refletir as novas diretrizes de proteção de dados e privacidade (LGPD). Essas mudanças visam dar mais transparência sobre como armazenamos e processamos suas informações cadastrais. Você não precisa tomar nenhuma ação. Atenciosamente, Departamento Jurídico",
    "Bom dia, Seu Antenor, Tudo bem? Segue o orçamento para a pintura das três salas e dos dois quartos do apartamento conforme combinamos na vistoria técnica. O valor já inclui o material de preparação (massa corrida e lixas). As tintas ficam por conta do proprietário. Fico no aguardo da aprovação para agendar a data. Marcos Pinturas ME",
    "Professor, boa tarde. Estou modelando um sistema de controle financeiro pessoal e optei por usar o SQLite como banco local. No entanto, tenho uma dúvida: considerando uma base para duas pessoas com histórico de 5 anos de transações, corro o risco de estourar a capacidade física do arquivo do banco? Há alguma perda brusca de performance? Obrigado, Luis Torres",
    "Você recebeu um PIX! Valor: R$ 350,00 Origem: Fernando Oliveira Instituição: Banco Central S.A. Data/Hora: 24/05/2026 - 15:30 O saldo já está disponível na sua conta corrente e pode ser consultado pelo nosso internet banking. Notificações BancoDigital",
    "Time de SecOps, O scanner automático do SonarQube e do Trivy rodou na última madrugada na nossa stack de containers. Foram encontradas duas vulnerabilidades de severidade 'Alta' na imagem base do Docker de um dos nossos microsserviços em Angular. Segue a lista detalhada para aplicação dos patches. Felipe Costa Analista de DevOps",
    "E aí, cara, beleza? Lembra que na semana passada a gente estava discutindo sobre como estruturar as camadas de Services e Repositories do projeto novo de forma desacoplada? Achei aquele livro do Robert C. Martin que te comentei. O PDF/Link está na minha pasta compartilhada, dá uma lida nos capítulos 5 e 6 que clareia muito a mente. Valeu, abraço! Rodrigo",
    "Prezada NetTelecom, Por meio deste e-mail, venho solicitar formalmente o cancelamento do meu plano de internet residencial (Contrato nº 48102-9), motivado por minha mudança de endereço para uma região que infelizmente não possui cobertura da sua rede de fibra. Solicito o envio da última fatura proporcional para o fechamento. Atenciosamente, Luis Paulo F. A."
]

