# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando a Inteligência Artificial no Google Colab
"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')
client = genai.Client()
chat = client.chats.create(model="gemini-2.5-flash")

prompt = input("Luis: ")
print()

while "tchau" not in prompt.lower():
  resposta = chat.send_message(prompt)

  print(f"InAr: {resposta.text}")
  print()

  prompt = input("Luis: ")
  print()

"""# Função Resumidora de E-mails"""

conteudos = [
    "Prezados, Seguem em anexo as notas e os principais pontos decididos na reunião de hoje de manhã sobre o Projeto Fênix. Por favor, revisem as tarefas atribuídas a cada um e atualizem o status no Jira até sexta-feira. Atenciosamente, Carlos Silva Gerente de Projetos",
    "Olá, Luis! Sua inscrição no 'Workshop Avançado de Python: Do Dev ao DevOps' foi confirmada com sucesso! O evento acontecerá de forma online no dia 15 de Junho, às 19h. O link de acesso à transmissão será enviado 1 hora antes do início. Até lá! Equipe TechLearn",
    "Olá, Boas notícias! Seu pedido já foi processado pela nossa logística e está a caminho. Você pode rastrear a entrega utilizando o código de rastreamento: BR837462910X. Obrigado por comprar conosco! Suporte E-Commerce Modas",
    "Prezada equipe, Informamos que no próximo domingo, entre 02:00 e 06:00 (horário de Brasília), nossa infraestrutura passará por uma manutenção preventiva na nuvem. Durante esse período, o banco de dados e as APIs do portal de cobrança estarão temporariamente indisponíveis. Contamos com a compreensão de todos. Time de DevOps e Infraestrutura",
    "Oi, família! Passando para lembrar que este domingo vamos comemorar o aniversário da vó na churrascaria do costume. Por favor, me confirmem quem vai até quinta para eu poder fechar o número exato de lugares na reserva. Beijos, Mariana"
]

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')
client = genai.Client()

def resumir_emails(conteudos):
  for numero, conteudo in enumerate(conteudos):
    resposta = client.models.generate_content(
        model = "gemini-3.5-flash",
        contents = f"""Vou te mandar o corpo de um e-mail.
                      Quero que você resuma este corpo em apenas 150 caracteres, passando o intuito daquele e-mail.
                      Segue o conteúdo: {conteudo}"""
    )
    print(f"E-mail #{numero + 1}: {resposta.text}")
    print("-" * 3)

resumir_emails(conteudos)

