# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando Groq no Colab
"""

!pip install -q groq

import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client = Groq()
completion = client.chat.completions.create(
    # model="llama-3.3-70b-versatile",
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "O que é IA?"
      }
    ],
    temperature=1,
    max_completion_tokens=1024,
    top_p=1,
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

