# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Rodando Groq no Colab
"""

!pip install -q groq

import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()
completion = client.chat.completions.create(
    # model="llama-3.3-70b-versatile",
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "O que é IA?"
      }
    ],
    temperature=1,
    max_completion_tokens=1024,
    top_p=1,
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")



"""# Leitura e Escrita de Arquivos"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

client = genai.Client()

corpos_emails = [
    "Prezados, Seguem em anexo as notas e os principais pontos decididos na reunião de hoje de manhã sobre o Projeto Fênix. Por favor, revisem as tarefas atribuídas a cada um e atualizem o status no Jira até sexta-feira. Atenciosamente, Carlos Silva Gerente de Projetos",
    "Olá, Luis! Sua inscrição no 'Workshop Avançado de Python: Do Dev ao DevOps' foi confirmada com sucesso! O evento acontecerá de forma online no dia 15 de Junho, às 19h. O link de acesso à transmissão será enviado 1 hora antes do início. Até lá! Equipe TechLearn",
    "Olá, Boas notícias! Seu pedido já foi processado pela nossa logística e está a caminho. Você pode rastrear a entrega utilizando o código de rastreamento: BR837462910X. Obrigado por comprar conosco! Suporte E-Commerce Modas",
    "Prezada equipe, Informamos que no próximo domingo, entre 02:00 e 06:00 (horário de Brasília), nossa infraestrutura passará por uma manutenção preventiva na nuvem. Durante esse período, o banco de dados e as APIs do portal de cobrança estarão temporariamente indisponíveis. Contamos com a compreensão de todos. Time de DevOps e Infraestrutura",
    "Oi, família! Passando para lembrar que este domingo vamos comemorar o aniversário da vó na churrascaria do costume. Por favor, me confirmem quem vai até quinta para eu poder fechar o número exato de lugares na reserva. Beijos, Mariana"
]

def obter_emails_resumidos(corpos):
  resumos = []

  for numero, corpo in enumerate(corpos):
    resposta = client.models.generate_content(
        model = "gemini-2.5-flash",
        contents = f"""Vou te mandar o corpo de um e-mail.
                       Quero que você o resuma em apenas 100 caracteres, passando o intuito da mensagem.
                       Segue o corpo do e-mail: {corpo}"""
    )

    resumo = f"E-mail {numero + 1}: {resposta.text}"
    resumos.append(resumo)

    print(resumo)
    print("-" * 3)

  return resumos
#

emails_resumidos = obter_emails_resumidos(corpos_emails)

emails_resumidos

with open("emails_resumidos.txt", "w", encoding="utf-8") as arquivo:
  for email in emails_resumidos:
    arquivo.write(email + "\n")

emails_recebidos = []

with open("emails_resumidos.txt", "r", encoding="utf-8") as arquivo:
  for linha in arquivo:
    emails_recebidos.append(linha.strip())

emails_recebidos

emails_recebidos = ""

with open("emails_resumidos.txt", "r", encoding="utf-8") as arquivo:
  emails_recebidos = arquivo.read()

emails_recebidos

emails_recebidos = ""

with open("emails_resumidos.txt", "r", encoding="utf-8") as arquivo:
  emails_recebidos = arquivo.readlines()

emails_recebidos

