# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Inicialização do Groq
"""

!pip install -q groq

import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()

resposta = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
      {
        "role": "user",
        "content": "O que é IA?"
      }
    ],
    temperature=1,
    max_completion_tokens=1024,
    top_p=1,
    stream=True,
    stop=None
)

"""# Inicialização do Gemini"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

client_gemini = genai.Client()

resposta = client_gemini.models.generate_content(
    model = "gemini-2.5-flash",
    contents = f"""O que é IA?"""
)

"""# Manipulação de Dados com o Pandas"""

import pandas as pd

df = pd.read_csv("/content/alunos.csv")

df.head()

"""# Aplicação Prática com o Pandas"""

