# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Inicialização do Groq
"""

!pip install -q groq

import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()

resposta = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
      {
        "role": "user",
        "content": "O que é IA?"
      }
    ],
    temperature=1,
    max_completion_tokens=1024,
    top_p=1,
    stream=True,
    stop=None
)

"""# Inicialização do Gemini"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

client_gemini = genai.Client()

resposta = client_gemini.models.generate_content(
    model = "gemini-2.5-flash",
    contents = f"""O que é IA?"""
)

"""# Manipulação de Dados com o Pandas"""

import pandas as pd

"""# Aplicação Prática com o Pandas"""

# Etapa 1 - Salvando 5 perguntas em um arquivo

perguntas = [
    "O que é IA?",
    "Como aprender com IA?",
    "Como usar IA para melhorar a vida?",
    "Como ganhar dinheiro com IA?",
    "Como usar IA para ajudar na educação?"
]

with open("perguntas.txt", "w", encoding="utf-8") as arquivo:
    for pergunta in perguntas:
        arquivo.write(f"{pergunta}\n")

# Etapa 2 - Lendo as 5 perguntas do arquivo salvo

lista_perguntas = []

with open("perguntas.txt", "r", encoding="utf-8") as arquivo:
    for linha in arquivo:
        lista_perguntas.append(linha.strip())

print(lista_perguntas)

# Etapa 3 - Obtendo as respostas das perguntas via Gemini

questionario = []
mensagens = []

for pergunta in lista_perguntas:
  mensagens.append({"role": "user", "content": f"Gere uma resposta muito sucinta para esta pergunta: {pergunta}"})

  texto = client_groq.chat.completions.create(
          model="llama-3.3-70b-versatile",
          messages=mensagens,
          temperature=1,
          max_completion_tokens=1024,
          top_p=1,
          stream=True,
          stop=None
      )

  resposta_completa = ""
  for pedaco in texto:
      conteudo = pedaco.choices[0].delta.content or ""
      resposta_completa += conteudo

  questionario.append({"pergunta": pergunta, "resposta": resposta_completa})

# Etapa 4.1 - Criando um CSV do questionário manualmente

import csv

with open("questionario_1.csv", "w", encoding="utf-8") as arquivo:
  writer = csv.writer(arquivo)
  writer.writerow(["Pergunta", "Resposta"])
  for questao in questionario:
    writer.writerow([questao['pergunta'], questao['resposta']])

# Etapa 4.2 - Criando um CSV do questionário com o Pandas

dataframe = pd.DataFrame(questionario)
dataframe.to_csv("questionario_2.csv", index=False, encoding="utf-8")

dataframe

