# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Inicialização do Groq
"""

!pip install -q groq

import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()

resposta = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
      {
        "role": "user",
        "content": "O que é IA?"
      }
    ],
    temperature=1,
    max_completion_tokens=1024,
    top_p=1,
    stream=True,
    stop=None
)

"""# Inicialização do Gemini"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

client_gemini = genai.Client()

resposta = client_gemini.models.generate_content(
    model = "gemini-2.5-flash",
    contents = f"""O que é IA?"""
)

"""# Manipulação de Dados com o Pandas"""

import pandas as pd
import numpy as np

np.random.seed(42)

produtos = ["Notebook", "Smartphone", "Tablet", "Monitor", "Teclado", "Mouse",
            "Headset", "Webcam", "SSD", "Pendrive", "Impressora", "Roteador",
            "Smart TV", "Caixa de Som", "Carregador"]

categorias_por_produto = {
    "Notebook": "Computadores", "Smartphone": "Telefonia", "Tablet": "Telefonia",
    "Monitor": "Computadores", "Teclado": "Periféricos", "Mouse": "Periféricos",
    "Headset": "Áudio", "Webcam": "Periféricos", "SSD": "Armazenamento",
    "Pendrive": "Armazenamento", "Impressora": "Escritório", "Roteador": "Redes",
    "Smart TV": "Entretenimento", "Caixa de Som": "Áudio", "Carregador": "Acessórios"
}

nomes = np.random.choice(produtos, size=50)

df = pd.DataFrame({
    "Nome do Produto":    nomes,
    "Categoria":         [categorias_por_produto[n] for n in nomes],
    "Quantidade Vendida": np.random.randint(1, 500, size=50),
    "Preço":             np.round(np.random.uniform(19.90, 4999.90, size=50), 2),
    "Avaliação":         np.round(np.random.uniform(1.0, 5.0, size=50), 1)
})

df.head()

df["Categoria"].unique()

