# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Inicialização do Groq
"""

!pip install -q groq

import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()

resposta = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
      {
        "role": "user",
        "content": "O que é IA?"
      }
    ],
    temperature=1,
    max_completion_tokens=1024,
    top_p=1,
    stream=True,
    stop=None
)

"""# Inicialização do Gemini"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

client_gemini = genai.Client()

resposta = client_gemini.models.generate_content(
    model = "gemini-2.5-flash",
    contents = f"""O que é IA?"""
)

"""# Manipulação de Dados com o Pandas"""

# Etapa 1 - Carregamento do reviews.csv

import pandas as pd

df = pd.read_csv('/content/reviews.csv')

reviews = df['reviewText']
analises = []

# Etapa 2 - Utilizar LLM para obter os sentimentos individuais

for numero, review in enumerate(reviews):
    resposta = client_groq.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": f"""Você irá analisar a resenha que te mandei abaixo, e irá retornar com uma análise de sentimento.
                               Responda apenas com uma das seguintes palavras: 'Positiva', 'Negativa', 'Neutra'.
                               Desta forma, você irá indicar o sentimento relativo àquela resenha específica.

                               Exemplos:
                               'Eu adorei este produto.' -> Positiva
                               'Gostei, mas não é nada de especial.' -> Neutra
                               'Odiei este produto.' -> Negativa

                               Segue a resenha a ser analisada: {review}"""
            }
        ],
        temperature=1,
        max_completion_tokens=10,
        top_p=1,
        stream=False
    )

    sentimento = resposta.choices[0].message.content.strip()
    analises.append(sentimento)
    print(f"Resenha {numero + 1}: '{review}' -> Sentimento: {sentimento}")

# Etapa 3 - Adicionar ao Data Frame uma nova coluna com estas classificações

reviews

df["sentimento"] = analises

df

