# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Inicialização do Groq
"""

!pip install -q groq

import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()

resposta = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
      {
        "role": "user",
        "content": "O que é IA?"
      }
    ],
    temperature=1,
    max_completion_tokens=1024,
    top_p=1,
    stream=True,
    stop=None
)

"""# Inicialização do Gemini"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

client_gemini = genai.Client()

resposta = client_gemini.models.generate_content(
    model = "gemini-2.5-flash",
    contents = f"""O que é IA?"""
)

"""# Inicialização do Pandas"""

# Etapa 1 - Carregamento do reviews.csv

import pandas as pd

df = pd.read_csv('/content/reviews.csv')

"""# Tratamento de Erros"""

try:
  idade = int(input("Digite a sua idade: "))
  numero_magico = 25 / idade;
  print()
  print(f'O número mágico da sua idade é {numero_magico}')
except ValueError as ve:
  print('\nErro: Você não digitou um inteiro válido.')
  print('Detalhes:', ve)
except TypeError as te:
  print('\nErro: Não é possível somar um inteiro com uma string.')
  print('Detalhes:', te)
except Exception as e:
  print('\nErro:', e)
finally:
  print("\nFinalizando o processo.")

