# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

# Inicialização do Groq
"""

!pip install -q groq

import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()

resposta = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
      {
        "role": "user",
        "content": "O que é IA?"
      }
    ],
    temperature=1,
    max_completion_tokens=1024,
    top_p=1,
    stream=True,
    stop=None
)

"""# Inicialização do Gemini"""

import os
from google.colab import userdata
from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

client_gemini = genai.Client()

resposta = client_gemini.models.generate_content(
    model = "gemini-2.5-flash",
    contents = f"""O que é IA?"""
)

"""# Inicialização do Pandas"""

# Etapa 1 - Carregamento do reviews.csv

import pandas as pd

df = pd.read_csv('/content/reviews.csv')

# Etapa 2 - Utilizar LLM para obter os sentimentos individuais e criando coluna nova

reviews = df['reviewText']
analises = []

for numero, review in enumerate(reviews):
    resposta = client_groq.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": f"""Você irá analisar a resenha que te mandei abaixo, e irá retornar com uma análise de sentimento.
                               Responda apenas com uma das seguintes palavras: 'Positiva', 'Negativa', 'Neutra'.
                               Desta forma, você irá indicar o sentimento relativo àquela resenha específica.

                               Exemplos:
                               'Eu adorei este produto.' -> Positiva
                               'Gostei, mas não é nada de especial.' -> Neutra
                               'Odiei este produto.' -> Negativa

                               Segue a resenha a ser analisada: {review}"""
            }
        ],
        temperature=1,
        max_completion_tokens=10,
        top_p=1,
        stream=False
    )

    sentimento = resposta.choices[0].message.content.strip()
    analises.append(sentimento)
    print(f"Resenha {numero + 1}: '{review}' -> Sentimento: {sentimento}")

df["sentimento"] = analises
df_negativas = df[df["sentimento"] == "Negativa"]
resenhas_negativas = df_negativas["reviewText"]
texto_resenhas_negativas = "#####".join(resenhas_negativas)

resposta = client_gemini.models.generate_content(
    model = "gemini-2.5-flash",
    contents = f"""Você é um analista de dados.
                   Vou te passar muitas resenhas negativas de análises de um produto separadas por '#####'.
                   Encontre 5 categorias diferentes para os tipos de reclamações.
                   Quero que você me retorne as 5 categorias.
                   Cada categoria deve ser definida por APENAS uma palavra, sem descrições.
                   Não escreva nada mais além das cinco categorias.
                   Quero que elas sejam retornadas separadas por vírgula, em letras minúsculas e sem acentos gráficos.

                   Exemplo: 'eletronicos, roupas, viagens, brinquedos'

                   Aqui estão as resenhas negativas: {texto_resenhas_negativas}"""
)

categorias = resposta.text.split(sep=", ")