# -*- coding: utf-8 -*-
"""Python com Inteligência Artificial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159oj_694rAG4lXPfUzQkDlBi6pMjmuN3

Começando a Aula de Python
"""

5

print(5);

print("Olá, mundo!");

produto1 = "Macarrão"

print(produto1);

produto2 = "Celular"

print(produto2);

produto3 = "Chocolate"

preco1 = 5

preco2 = 2000

preco3 = 1

print(preco1 + preco2 + preco3);

print(produto1, produto2, produto3);

amigos = 5;
aluguel = 1000;
supermercado = 500;
carro = 400;

total = aluguel + supermercado + carro;

print("Total R$", total);

alguel = 900;
total = aluguel + supermercado + carro;
print("Total R$", total);

aluguel -= 100;
total = aluguel + supermercado + carro;
print("Total R$", total);

amigos = 6;
aluguel = 1000;
supermercado = 500;
carro = 400;

total = ((carro * 2) + supermercado + aluguel) / amigos;

print(total);

type(amigos);

type(aluguel);

print(type(aluguel));

type(carro);

type(amigos)

type(total)

type(produto1)

type(produto2)

produto1 = "Macarrão"
produto2 = "Celular"
produto3 = "Chocolate"

type(produto1)

tem_carteira_motorista = True

type(tem_carteira_motorista)



"""Inicial: " Luis PAulo torres de OLIVEIRA "<br>
Final: "LUIS PAULO TORRES DE OLIVEIRA"
"""

texto = "          Luis PAulo torres de OLIVEIRA ";
print(texto);

texto_lower = texto.lower();
print(texto_lower);

print(texto.upper())

print(texto.strip())

print(texto.replace("  ", " "));

texto = texto.replace("  ", " ");

print(texto);

texto = texto.strip();

print(texto);

texto = texto.upper();
print(texto);

input("Digite o seu nome ");

input("Digite o seu nome ")

nome = input("Digite o nome: ")

idade = input("Digite a idade: ")

type(nome)

type(idade)

idade = int(idade)

type(idade)

print("A pessoa se chama ", nome, " e tem ", idade, "anos")

print("A pessoa se chama", nome, "e tem", idade, "anos")

print(f"A pessoa se chama {nome} e tem {idade} anos de idade.")



"""Estruturas Condicionais"""

nome = input("Digite em nome: ")

idade = int(input("Digite a sua idade: "))

if idade >= 18:
  print(f"{nome} pode entrar na festa, pois ele é maior de idade.")
  print(f"Ele tem {idade} anos.")
else:
  print(f"{nome} não pode entrar na festa, pois ele é menor de idade.")
  print(f"Ele tem {idade} anos.")

media = float(input("Digite a sua média: "))

if media >= 7.0:
  print("Aprovado")
elif media >= 5.0:
  print("Recuperação")
else:
  print("Reprovado")

media = float(input("Digite a sua média: "))

if media < 5.0:
  print("Reprovado!")
elif media >= 5.0 and media <= 7.9:
  print("Recuperação!")
else:
  print("Aprovado!")

"""# Rodando a Inteligência Artificial no Google Colab"""

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

from google import genai

client = genai.Client()

resposta = client.models.generate_content(model="gemini-2.5-flash", contents="Minha página no Instagram está crescendo, e estou tendo dificuldades em responder aos comentários e mensagens como antes. Como posso fazer para me manter próximo ao meu público dentro deste cenário?")

print(resposta.text)